// Catalog of metadata types for the Metadata Explorer tab.
// Each entry defines its query (tooling or data API) and the columns to show.
// `namespace: true` means the sObject has a NamespacePrefix field — a Namespace
// column is added automatically (and the field injected into the query).

export interface MetaColumn { key: string; label: string; }
export interface MetaType { id: string; label: string; icon: string; tooling: boolean; soql: string; columns: MetaColumn[]; idField?: string; namespace?: boolean; }

export const METADATA_CATALOG: MetaType[] = [
  { id: 'ApexClass', label: 'Apex Classes', icon: '📦', tooling: true, namespace: true, soql: "SELECT Name, ApiVersion, LengthWithoutComments, Status, LastModifiedDate FROM ApexClass ORDER BY Name LIMIT 2000", columns: [{ key: 'Name', label: 'Name' }, { key: 'ApiVersion', label: 'API' }, { key: 'LengthWithoutComments', label: 'Length' }, { key: 'Status', label: 'Status' }, { key: 'LastModifiedDate', label: 'Modified' }] },
  { id: 'ApexTrigger', label: 'Apex Triggers', icon: '⚡', tooling: true, namespace: true, soql: "SELECT Name, TableEnumOrId, ApiVersion, Status, LastModifiedDate FROM ApexTrigger ORDER BY Name LIMIT 2000", columns: [{ key: 'Name', label: 'Name' }, { key: 'TableEnumOrId', label: 'Object' }, { key: 'ApiVersion', label: 'API' }, { key: 'Status', label: 'Status' }, { key: 'LastModifiedDate', label: 'Modified' }] },
  { id: 'ApexPage', label: 'Visualforce Pages', icon: '📄', tooling: true, namespace: true, soql: "SELECT Name, MasterLabel, ApiVersion, LastModifiedDate FROM ApexPage ORDER BY Name LIMIT 2000", columns: [{ key: 'Name', label: 'Name' }, { key: 'MasterLabel', label: 'Label' }, { key: 'ApiVersion', label: 'API' }, { key: 'LastModifiedDate', label: 'Modified' }] },
  { id: 'ApexComponent', label: 'VF Components', icon: '🧱', tooling: true, namespace: true, soql: "SELECT Name, MasterLabel, ApiVersion, LastModifiedDate FROM ApexComponent ORDER BY Name LIMIT 2000", columns: [{ key: 'Name', label: 'Name' }, { key: 'MasterLabel', label: 'Label' }, { key: 'ApiVersion', label: 'API' }, { key: 'LastModifiedDate', label: 'Modified' }] },
  { id: 'AuraDefinitionBundle', label: 'Aura Components', icon: '🟦', tooling: true, namespace: true, soql: "SELECT DeveloperName, MasterLabel, ApiVersion, LastModifiedDate FROM AuraDefinitionBundle ORDER BY DeveloperName LIMIT 2000", columns: [{ key: 'DeveloperName', label: 'Name' }, { key: 'MasterLabel', label: 'Label' }, { key: 'ApiVersion', label: 'API' }, { key: 'LastModifiedDate', label: 'Modified' }] },
  { id: 'LightningComponentBundle', label: 'Lightning Web Components', icon: '🔆', tooling: true, namespace: true, soql: "SELECT DeveloperName, MasterLabel, ApiVersion FROM LightningComponentBundle ORDER BY DeveloperName LIMIT 2000", columns: [{ key: 'DeveloperName', label: 'Name' }, { key: 'MasterLabel', label: 'Label' }, { key: 'ApiVersion', label: 'API' }] },
  { id: 'CustomObject', label: 'Custom Objects', icon: '🗃️', tooling: true, namespace: true, soql: "SELECT DeveloperName, ManageableState FROM CustomObject ORDER BY DeveloperName LIMIT 2000", columns: [{ key: 'DeveloperName', label: 'Name' }, { key: 'ManageableState', label: 'State' }] },
  { id: 'CustomField', label: 'Custom Fields', icon: '🔤', tooling: true, namespace: true, soql: "SELECT DeveloperName, TableEnumOrId FROM CustomField ORDER BY TableEnumOrId LIMIT 2000", columns: [{ key: 'DeveloperName', label: 'Field' }, { key: 'TableEnumOrId', label: 'Object' }] },
  { id: 'ValidationRule', label: 'Validation Rules', icon: '✅', tooling: true, namespace: true, soql: "SELECT ValidationName, Active, ErrorMessage FROM ValidationRule ORDER BY ValidationName LIMIT 2000", columns: [{ key: 'ValidationName', label: 'Name' }, { key: 'Active', label: 'Active' }, { key: 'ErrorMessage', label: 'Error Message' }] },
  { id: 'FlowDefinitionView', label: 'Flows', icon: '🌊', tooling: false, idField: 'DurableId', namespace: true, soql: "SELECT DurableId, ApiName, Label, ProcessType, TriggerType, IsActive FROM FlowDefinitionView ORDER BY Label LIMIT 2000", columns: [{ key: 'Label', label: 'Label' }, { key: 'ApiName', label: 'API Name' }, { key: 'ProcessType', label: 'Type' }, { key: 'TriggerType', label: 'Trigger' }, { key: 'IsActive', label: 'Active' }] },
  { id: 'PermissionSet', label: 'Permission Sets', icon: '🛡️', tooling: false, namespace: true, soql: "SELECT Name, Label, IsOwnedByProfile FROM PermissionSet ORDER BY Name LIMIT 2000", columns: [{ key: 'Label', label: 'Label' }, { key: 'Name', label: 'API Name' }, { key: 'IsOwnedByProfile', label: 'Profile-owned' }] },
  { id: 'Profile', label: 'Profiles', icon: '👤', tooling: false, soql: "SELECT Name, UserType FROM Profile ORDER BY Name LIMIT 2000", columns: [{ key: 'Name', label: 'Name' }, { key: 'UserType', label: 'User Type' }] },
  { id: 'CustomPermission', label: 'Custom Permissions', icon: '🔑', tooling: true, namespace: true, soql: "SELECT DeveloperName, MasterLabel FROM CustomPermission ORDER BY DeveloperName LIMIT 2000", columns: [{ key: 'DeveloperName', label: 'Name' }, { key: 'MasterLabel', label: 'Label' }] },
  { id: 'ExternalString', label: 'Custom Labels', icon: '🏷️', tooling: true, namespace: true, soql: "SELECT Name, MasterLabel, Category, Language FROM ExternalString ORDER BY Name LIMIT 2000", columns: [{ key: 'Name', label: 'Name' }, { key: 'MasterLabel', label: 'Label' }, { key: 'Category', label: 'Category' }, { key: 'Language', label: 'Lang' }] },
  { id: 'StaticResource', label: 'Static Resources', icon: '📎', tooling: true, namespace: true, soql: "SELECT Name, ContentType, BodyLength, LastModifiedDate FROM StaticResource ORDER BY Name LIMIT 2000", columns: [{ key: 'Name', label: 'Name' }, { key: 'ContentType', label: 'Content Type' }, { key: 'BodyLength', label: 'Size (bytes)' }, { key: 'LastModifiedDate', label: 'Modified' }] },
  { id: 'EmailTemplate', label: 'Email Templates', icon: '✉️', tooling: false, namespace: true, soql: "SELECT Name, DeveloperName, FolderName, TemplateType FROM EmailTemplate ORDER BY Name LIMIT 2000", columns: [{ key: 'Name', label: 'Name' }, { key: 'DeveloperName', label: 'API Name' }, { key: 'FolderName', label: 'Folder' }, { key: 'TemplateType', label: 'Type' }] },
  { id: 'Report', label: 'Reports', icon: '📊', tooling: false, soql: "SELECT Name, FolderName, Format FROM Report ORDER BY Name LIMIT 2000", columns: [{ key: 'Name', label: 'Name' }, { key: 'FolderName', label: 'Folder' }, { key: 'Format', label: 'Format' }] },
  { id: 'Dashboard', label: 'Dashboards', icon: '📈', tooling: false, soql: "SELECT Title, FolderName FROM Dashboard ORDER BY Title LIMIT 2000", columns: [{ key: 'Title', label: 'Title' }, { key: 'FolderName', label: 'Folder' }] },
  { id: 'CronTrigger', label: 'Scheduled Jobs', icon: '⏰', tooling: false, soql: "SELECT CronJobDetail.Name, State, NextFireTime, PreviousFireTime FROM CronTrigger ORDER BY NextFireTime LIMIT 2000", columns: [{ key: 'CronJobDetail.Name', label: 'Job' }, { key: 'State', label: 'State' }, { key: 'NextFireTime', label: 'Next Run' }, { key: 'PreviousFireTime', label: 'Last Run' }] },
  { id: 'ApexTestRunResult', label: 'Test History', icon: '🧪', tooling: true, soql: "SELECT JobName, Status, StartTime, TestTime, ClassesCompleted, MethodsCompleted, MethodsFailed FROM ApexTestRunResult ORDER BY StartTime DESC LIMIT 1000", columns: [{ key: 'JobName', label: 'Job' }, { key: 'Status', label: 'Status' }, { key: 'StartTime', label: 'Started' }, { key: 'TestTime', label: 'Time (ms)' }, { key: 'MethodsCompleted', label: 'Passed' }, { key: 'MethodsFailed', label: 'Failed' }] },
];
